language: python
sudo: required
python:
    - 3.5
    - nightly

services:
    - docker

install:
    - pip install --upgrade setuptools
    - pip install coveralls
    - pip install -Ur requirements-dev.txt
    - python setup.py develop

script:
    make ci
after_success:
    coveralls

env:
    matrix:
        - PYTHONASYNCIODEBUG=x
        - PYTHONASYNCIODEBUG=
