language: python
sudo: required
python:
    - 3.5

services:
    - docker

before_install:
    - nvm install node
    - nvm use node
    - npm i -g yarn@0.16.1

install:
    - pip install --upgrade setuptools
    - pip install codecov
    - pip install -Ur requirements-dev.txt
    - python setup.py develop
    - yarn install

script:
    make ci
after_success:
    codecov

env:
    matrix:
        - PYTHONASYNCIODEBUG=x
        - PYTHONASYNCIODEBUG=
